---
book_repo: pivotal-cf/docs-book-healthwatch
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-pcf-healthwatch
    ref: '1.5'
  directory: pcf-healthwatch/1-5
  subnav_template: pcf_healthwatch_1_5_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Healthwatch
    search_placeholder: Search PCF Healthwatch
    url_prefix: pcf-healthwatch/1-5
    local_product_version: 1.5
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-0
        display_name: v1.0  

- repository:
    name: pivotal-cf/docs-pcf-healthwatch
    ref: '1.4'
  directory: pcf-healthwatch/1-4
  subnav_template: pcf_healthwatch_1_4_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: https://docs.pivotal.io/pcf-healthwatch/1-4/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Healthwatch
    search_placeholder: Search PCF Healthwatch
    url_prefix: pcf-healthwatch/1-4
    local_product_version: 1.4
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-pcf-healthwatch
    ref: '1.3'
  directory: pcf-healthwatch/1-3
  subnav_template: pcf_healthwatch_1_3_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: https://docs.pivotal.io/pcf-healthwatch/1-3/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Healthwatch
    search_placeholder: Search PCF Healthwatch
    url_prefix: pcf-healthwatch/1-3
    local_product_version: 1.3
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-pcf-healthwatch
    ref: '1.2'
  directory: pcf-healthwatch/1-2
  subnav_template: pcf_healthwatch_1_2_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: https://docs.pivotal.io/pcf-healthwatch/1-2/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Healthwatch
    search_placeholder: Search PCF Healthwatch
    url_prefix: pcf-healthwatch/1-2
    local_product_version: 1.2
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-pcf-healthwatch
    ref: '1.1'
  directory: pcf-healthwatch/1-1
  subnav_template: pcf_healthwatch_1_1_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: https://docs.pivotal.io/pcf-healthwatch/1-1/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Healthwatch
    search_placeholder: Search PCF Healthwatch
    url_prefix: pcf-healthwatch/1-1
    local_product_version: 1.1
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-pcf-healthwatch
    ref: '1.0'
  directory: pcf-healthwatch/1-0
  subnav_template: pcf_healthwatch_1_0_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.5
    changelog_href: https://docs.pivotal.io/pcf-healthwatch/1-0/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Healthwatch
    search_placeholder: Search PCF Healthwatch
    url_prefix: pcf-healthwatch/1-0
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-4
        display_name: v1.4
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/pcf-healthwatch/1-1
        display_name: v1.1
